apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-faiss-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: py-faiss-api
  template:
    metadata:
      labels:
        app: py-faiss-api
    spec:
      containers:
        - name: py-faiss-api
          image: py-faiss-api:latest
          ports:
            - containerPort: 8000

          # 健康检查配置
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          startupProbe:
            httpGet:
              path: /health/startup
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"